// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tayseer.Api.Data;

#nullable disable

namespace Tayseer.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tayseer.Api.Domain.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdminUsers", (string)null);
                });

            modelBuilder.Entity("Tayseer.Api.Domain.AgentConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedAdminUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTimeOffset?>("LastAgentMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastVisitorMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VisitorEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VisitorKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("VisitorName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAdminUserId");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("VisitorKey")
                        .IsUnique();

                    b.ToTable("AgentConversations", (string)null);
                });

            modelBuilder.Entity("Tayseer.Api.Domain.AgentMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminDisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sender")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("AgentMessages", (string)null);
                });

            modelBuilder.Entity("Tayseer.Api.Domain.ContactInquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Interest")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("ContactInquiries", (string)null);
                });

            modelBuilder.Entity("Tayseer.Api.Domain.Office", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            AddressAr = "مكتب 7، الطابق الثاني، مبنى سلام، طريق الأمير سعد بن عبدالرحمن الأول الفرعي، الروابي، الرياض، المملكة العربية السعودية",
                            AddressEn = "Office 7, 2nd Floor, Selam Building, Prince Saad bin Abdulrahman Alawal Branch Road, Al Rawabi, Riyadh, Kingdom of Saudi Arabia",
                            CountryCode = "SA",
                            Email = "info@tayseer.me",
                            Phone = "+966 555203079",
                            SortOrder = 1,
                            TitleAr = "المملكة العربية السعودية",
                            TitleEn = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            AddressAr = "601، ون ليك بلازا، الكلستر T، جميرا ليك تاورز، دبي، الإمارات",
                            AddressEn = "601, One Lake Plaza, Cluster T, JLT, Dubai, UAE",
                            CountryCode = "AE",
                            Email = "info@tayseer.me",
                            Phone = "+971 43997558",
                            SortOrder = 2,
                            TitleAr = "الإمارات العربية المتحدة",
                            TitleEn = "UAE"
                        });
                });

            modelBuilder.Entity("Tayseer.Api.Domain.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("MetaDescriptionAr")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("MetaDescriptionEn")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("Tayseer.Api.Domain.PageSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyAr")
                        .HasColumnType("text");

                    b.Property<string>("BodyEn")
                        .HasColumnType("text");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TitleAr")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TitleEn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("PageSections");
                });

            modelBuilder.Entity("Tayseer.Api.Domain.ServiceFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceOfferingId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceOfferingId");

                    b.ToTable("ServiceFeatures");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000a01"),
                            DescriptionAr = "بطاقات ومحافظ جوال ومدفوعات عبر التطبيقات بمعالجة آمنة وفعّالة.",
                            DescriptionEn = "Cards, mobile wallets, and app-based payments with secure, efficient processing.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111102"),
                            SortOrder = 1,
                            TitleAr = "المدفوعات",
                            TitleEn = "Payments"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000a02"),
                            DescriptionAr = "تحويلات مالية محلية ودولية سريعة وآمنة وفعّالة من حيث التكلفة.",
                            DescriptionEn = "Fast, secure, cost-effective domestic and international money transfers.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111102"),
                            SortOrder = 2,
                            TitleAr = "حلول التحويلات",
                            TitleEn = "Remittance Solutions"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000a03"),
                            DescriptionAr = "وصول حديث للحسابات وخدمات مصرفية عبر الإنترنت والجوال تبقي العملاء متفاعلين.",
                            DescriptionEn = "Modern account access, online banking, and mobile experiences that keep customers engaged.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111102"),
                            SortOrder = 3,
                            TitleAr = "الخدمات المصرفية للأفراد",
                            TitleEn = "Consumer Banking"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000a04"),
                            DescriptionAr = "ضوابط قوية تلبي اللوائح المتطورة وتحمي النزاهة المالية.",
                            DescriptionEn = "Robust controls that meet evolving regulations and protect financial integrity.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111102"),
                            SortOrder = 4,
                            TitleAr = "الأمن والامتثال",
                            TitleEn = "Security & Compliance"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000a05"),
                            DescriptionAr = "حوّل بيانات العملاء إلى رؤى قابلة للتنفيذ لقرارات أذكى وولاء أعلى.",
                            DescriptionEn = "Turn customer data into actionable insights for smarter decisions and loyalty.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111102"),
                            SortOrder = 5,
                            TitleAr = "إدارة العملاء والتحليلات",
                            TitleEn = "CRM & BI Systems"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000a06"),
                            DescriptionAr = "البقاء متوافقاً مع اللوائح وقدرات التدقيق وفق أفضل الممارسات.",
                            DescriptionEn = "Stay compliant with industry regulations and best-practice audit capabilities.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111102"),
                            SortOrder = 6,
                            TitleAr = "التدقيق والتشريعات",
                            TitleEn = "Audit & Legislation"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000a07"),
                            DescriptionAr = "تحديد وقياس وتخفيف المخاطر التشغيلية والمالية عبر البنك.",
                            DescriptionEn = "Identify, measure, and mitigate operational and financial risk across the bank.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111102"),
                            SortOrder = 7,
                            TitleAr = "إدارة المخاطر",
                            TitleEn = "Risk Management"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000a08"),
                            DescriptionAr = "عمليات الخزينة والأموال للتحكم في السيولة والتسويات.",
                            DescriptionEn = "Treasury and funds operations that keep liquidity and settlements under control.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111102"),
                            SortOrder = 8,
                            TitleAr = "الأموال والخزينة",
                            TitleEn = "Funds & Treasury"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000b01"),
                            DescriptionAr = "يفسّر التعليمات بذكاء ثم ينفّذ العمليات من البداية إلى النهاية بدقة وسرعة.",
                            DescriptionEn = "Interprets instructions intelligently, then executes end-to-end operations with accuracy and speed.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111101"),
                            SortOrder = 1,
                            TitleAr = "تنفيذ موجّه بالأهداف",
                            TitleEn = "Goal-Oriented Execution"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000b02"),
                            DescriptionAr = "تحليل المستندات والتحقق من الأصالة لتسجيل متوافق وسلس.",
                            DescriptionEn = "Document analysis and authenticity checks for compliant, frictionless onboarding.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111101"),
                            SortOrder = 2,
                            TitleAr = "التسجيل الذكي / اعرف عميلك",
                            TitleEn = "Intelligent Onboarding / KYC"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000b03"),
                            DescriptionAr = "تفاعل شبه بشري مع دعم اللهجات العربية عبر القنوات.",
                            DescriptionEn = "Human-like interaction with native Arabic dialect support across channels.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111101"),
                            SortOrder = 3,
                            TitleAr = "تجربة صوت ودردشة",
                            TitleEn = "Voice & Chat Experience"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000b04"),
                            DescriptionAr = "نشر محلي أو عبر الحاويات مع قابلية توسع عند الطلب.",
                            DescriptionEn = "On-premise or containerized deployment with on-demand scalability.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111101"),
                            SortOrder = 4,
                            TitleAr = "نشر مرن",
                            TitleEn = "Flexible Deployment"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000b05"),
                            DescriptionAr = "يتصل بالوحدات الحالية دون تعطيل كبير.",
                            DescriptionEn = "Connects to existing business modules without major disruption.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111101"),
                            SortOrder = 5,
                            TitleAr = "تكامل الأنظمة",
                            TitleEn = "System Integration"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000c01"),
                            DescriptionAr = "التسجيل والمدفوعات والتحويلات والتحليلات في منصة واحدة بعلامتك.",
                            DescriptionEn = "Onboarding, payments, transfers, and analytics in one white-label stack.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111103"),
                            SortOrder = 1,
                            TitleAr = "منصة موحّدة",
                            TitleEn = "Unified Platform"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000c02"),
                            DescriptionAr = "الوصول للمجتمعات ضعيفة الاتصال عبر شبكة وكلاء وتدفقات دون اتصال.",
                            DescriptionEn = "Reach low-connectivity communities with agent networks and offline flows.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111103"),
                            SortOrder = 2,
                            TitleAr = "الوكلاء وUSSD",
                            TitleEn = "Agent Banking & USSD"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000c03"),
                            DescriptionAr = "انشر ما تحتاجه الآن وأضف القدرات مع النمو.",
                            DescriptionEn = "Deploy what you need now; add capabilities as you grow.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111103"),
                            SortOrder = 3,
                            TitleAr = "مرن وقابل للتوسع",
                            TitleEn = "Modular & Scalable"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000c04"),
                            DescriptionAr = "خدمات مصغّرة وأحداث فورية ومراقبة وضوابط أمنية قوية.",
                            DescriptionEn = "Microservices, real-time events, observability, and strong security controls.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111103"),
                            SortOrder = 4,
                            TitleAr = "أمن مؤسسي",
                            TitleEn = "Enterprise Security"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000c05"),
                            DescriptionAr = "مراقبة المعاملات وإدارة الوكلاء والامتثال وأدوات التقارير.",
                            DescriptionEn = "Transaction monitoring, agent management, compliance, and reporting tools.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111103"),
                            SortOrder = 5,
                            TitleAr = "لوحات المشغّل",
                            TitleEn = "Operator Dashboards"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000d01"),
                            DescriptionAr = "مستودعات مركزية وسجل تغييرات وتعاون برمجي بأدوات من فئة Git.",
                            DescriptionEn = "Central repositories, change history, and collaborative coding with Git-class tooling.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111105"),
                            SortOrder = 1,
                            TitleAr = "أنظمة التحكم بالإصدارات",
                            TitleEn = "Version Control Systems"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000d02"),
                            DescriptionAr = "بيئات تطوير ومصححات وأطر اختبار تسرّع التسليم.",
                            DescriptionEn = "IDEs, debuggers, and testing frameworks that accelerate delivery.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111105"),
                            SortOrder = 2,
                            TitleAr = "أدوات تطوير الجوال والبرمجيات",
                            TitleEn = "Mobile & Software Dev Tools"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000d03"),
                            DescriptionAr = "تخزين منظّم للكود والأصول وملفات المشاريع مع سجل الإصدارات.",
                            DescriptionEn = "Organized storage for code, assets, and project files with version history.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111105"),
                            SortOrder = 3,
                            TitleAr = "إدارة الملفات",
                            TitleEn = "File Management"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000d04"),
                            DescriptionAr = "ربط الأنظمة وأتمتة سير العمل وكسر صوامع البيانات.",
                            DescriptionEn = "Connect systems, automate workflows, and break down data silos.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111105"),
                            SortOrder = 4,
                            TitleAr = "إدارة واجهات التكامل",
                            TitleEn = "Integration API Management"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000d05"),
                            DescriptionAr = "خطوط بناء واختبار وإصدار مؤتمتة لفرق التقنية المالية.",
                            DescriptionEn = "Automated build, test, and release pipelines for FinTech teams.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111105"),
                            SortOrder = 5,
                            TitleAr = "أدوات التكامل والنشر المستمر",
                            TitleEn = "CI/CD Tooling"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000e01"),
                            DescriptionAr = "إدارة وتحسين الأداء والصيانة المستمرة لنظام T24.",
                            DescriptionEn = "Administration, performance optimization, and ongoing T24 maintenance.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111104"),
                            SortOrder = 1,
                            TitleAr = "إدارة T24 Temenos",
                            TitleEn = "Managed T24 Temenos"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000e02"),
                            DescriptionAr = "تخزين ومعالجة وتحليل مجموعات بيانات مالية كبيرة ومعقّدة.",
                            DescriptionEn = "Storage, processing, and analytics for large, complex financial datasets.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111104"),
                            SortOrder = 2,
                            TitleAr = "إدارة البيانات الضخمة",
                            TitleEn = "Big Data Management"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000e03"),
                            DescriptionAr = "مراقبة وكشف تهديدات واستجابة للحوادث للأنظمة الحرجة.",
                            DescriptionEn = "Monitoring, threat detection, and incident response for critical systems.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111104"),
                            SortOrder = 3,
                            TitleAr = "الأمن المُدار",
                            TitleEn = "Managed Security"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000e04"),
                            DescriptionAr = "صيانة استباقية واستجابة للحوادث لأجهزة النقد والصراف.",
                            DescriptionEn = "Proactive maintenance and incident response for cash and teller machines.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111104"),
                            SortOrder = 4,
                            TitleAr = "إدارة أجهزة الصراف وSTM",
                            TitleEn = "ATM & STM Management"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000e05"),
                            DescriptionAr = "عمليات سحابية وبنية تحتية تبقي المنصات موثوقة وفعّالة.",
                            DescriptionEn = "Cloud and infrastructure operations that keep platforms reliable and efficient.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111104"),
                            SortOrder = 5,
                            TitleAr = "عمليات IaaS / SaaS",
                            TitleEn = "IaaS / SaaS Operations"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000f01"),
                            DescriptionAr = "أجهزة صراف وإعادة تدوير GRG للسحب والإيداع ودفع الفواتير وإعادة تدوير النقد على مدار الساعة بشبكات عالية التوافر.",
                            DescriptionEn = "GRG ATMs and recyclers for 24/7 withdrawals, deposits, bill pay, and cash recycling built for high-availability networks.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111106"),
                            SortOrder = 1,
                            TitleAr = "أجهزة الصراف وإعادة تدوير النقد",
                            TitleEn = "ATMs & Cash Recyclers"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000f02"),
                            DescriptionAr = "خدمة ذاتية بمساعدة بشرية تختصر طوابير الفروع مع الإبقاء على رحلات مصرفية مدعومة.",
                            DescriptionEn = "Human-assisted self-service that shortens branch queues while keeping assisted banking journeys intact.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111106"),
                            SortOrder = 2,
                            TitleAr = "آلات الصراف الذكية (STM)",
                            TitleEn = "Smart Teller Machines (STMs)"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000f03"),
                            DescriptionAr = "تقنيات دقيقة للعد والفرز والتحقق لضمان عمليات نقد موثوقة في الفروع ومراكز النقد.",
                            DescriptionEn = "Accurate counting, sorting, and verification technology for reliable cash-ops in branches and cash centres.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111106"),
                            SortOrder = 3,
                            TitleAr = "فرز النقد ومعالجة الأوراق",
                            TitleEn = "Cash Sorting & Banknote Handling"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000f04"),
                            DescriptionAr = "أكشاك للفروع والصالات تتجاوز أجهزة الصراف — خدمات الحسابات والطلبات ورحلات عملاء سلسة.",
                            DescriptionEn = "Lobby and branch kiosks that extend beyond ATMs — account services, applications, and seamless customer journeys.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111106"),
                            SortOrder = 4,
                            TitleAr = "أجهزة الخدمة الذاتية المصرفية",
                            TitleEn = "Self-Service Banking Hardware"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-000000000f05"),
                            DescriptionAr = "وحدات مراقبة وتحقيق مدمجة تكشف مشكلات الإيداع والأجهزة بسرعة أكبر، مع رؤى في اليوم نفسه ودورات معالجة أقصر.",
                            DescriptionEn = "In-built monitoring and investigation modules that surface deposit and hardware issues faster, with same-day insight and shorter resolution cycles.",
                            ServiceOfferingId = new Guid("11111111-1111-1111-1111-111111111106"),
                            SortOrder = 5,
                            TitleAr = "المراقبة والتحقيق",
                            TitleEn = "Monitoring & Investigation"
                        });
                });

            modelBuilder.Entity("Tayseer.Api.Domain.ServiceOffering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BodyAr")
                        .HasColumnType("text");

                    b.Property<string>("BodyEn")
                        .HasColumnType("text");

                    b.Property<string>("CtaLabelAr")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CtaLabelEn")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CtaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconKey")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("ShortDescriptionAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShortDescriptionEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ServiceOfferings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            AccentColor = "green",
                            BodyAr = "فهيم منصة ذكاء اصطناعي وكيلية مصممة لإدارة وتحسين العمليات من البداية إلى النهاية لتعزيز تجربة العملاء.",
                            BodyEn = "Fahim is an Agentic AI platform engineered to manage and optimize end-to-end business operations for enhanced customer experience.",
                            CtaLabelAr = "تواصل معنا لعرض تجريبي",
                            CtaLabelEn = "Contact Us for Demo",
                            CtaUrl = "/solutions/fahim-ai",
                            IconKey = "ai",
                            IsPublished = true,
                            ShortDescriptionAr = "ذكاء يصنع تحولاً في أعمالك",
                            ShortDescriptionEn = "Intelligence to Revolutionize Your Business",
                            Slug = "fahim-ai",
                            SortOrder = 2,
                            TitleAr = "فهيم للذكاء الاصطناعي",
                            TitleEn = "Fahim AI",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            AccentColor = "blue",
                            BodyAr = "بسّط أنظمتك المصرفية الأساسية لتوجيه الموارد نحو ابتكار يركز على العميل.",
                            BodyEn = "Streamline your Core Banking so you can dedicate resources to customer-centric innovation.",
                            CtaLabelAr = "اعرف المزيد",
                            CtaLabelEn = "Learn More",
                            CtaUrl = "/solutions/core-banking",
                            IconKey = "core-banking",
                            IsPublished = true,
                            ShortDescriptionAr = "خدمات مصرفية أساسية للمستقبل ونمو بلا حدود.",
                            ShortDescriptionEn = "Future-Proof Core Banking. Growth Unleashed.",
                            Slug = "core-banking",
                            SortOrder = 1,
                            TitleAr = "الخدمات المصرفية الأساسية",
                            TitleEn = "Core Banking",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            AccentColor = "green",
                            BodyAr = "منصة مالية عبر الجوال بعلامتك التجارية مدعومة بالذكاء الاصطناعي مع التسجيل والمدفوعات والتحليلات والعمل دون اتصال.",
                            BodyEn = "AI-powered white-label mobile finance platform with onboarding, payments, analytics, and offline capability.",
                            CtaLabelAr = "تواصل معنا لعرض تجريبي",
                            CtaLabelEn = "Contact Us for Demo",
                            CtaUrl = "/solutions/mbuke",
                            IconKey = "mbuke",
                            IsPublished = true,
                            ShortDescriptionAr = "منصة خدمات مصرفية عبر الجوال بعلامتك التجارية",
                            ShortDescriptionEn = "White-Label Mobile Banking Platform",
                            Slug = "mbuke",
                            SortOrder = 3,
                            TitleAr = "إم بوكي",
                            TitleEn = "MBuke",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            AccentColor = "blue",
                            BodyAr = "دعم خبير لأنظمة T24 Temenos والأمن وأجهزة الصراف وSTMs والبيانات الضخمة والبنية السحابية.",
                            BodyEn = "Expert support for T24 Temenos, security, ATM/STM, big data, and cloud infrastructure.",
                            CtaLabelAr = "تحدث معنا",
                            CtaLabelEn = "Talk To Us",
                            CtaUrl = "/solutions/managed-services",
                            IconKey = "managed",
                            IsPublished = true,
                            ShortDescriptionAr = "أداء متميز عبر خبرات مُدارة.",
                            ShortDescriptionEn = "Peak Performance via Managed Expertise.",
                            Slug = "managed-services",
                            SortOrder = 5,
                            TitleAr = "الخدمات المُدارة",
                            TitleEn = "Managed Services",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            AccentColor = "blue",
                            BodyAr = "إدارة الإصدارات وأدوات التطوير وإدارة الملفات وواجهات البرمجة لفرق التقنية المالية.",
                            BodyEn = "Version control, development tooling, file and API management for FinTech teams.",
                            CtaLabelAr = "اعرف المزيد",
                            CtaLabelEn = "Learn More",
                            CtaUrl = "/solutions/software-management-systems",
                            IconKey = "software",
                            IsPublished = true,
                            ShortDescriptionAr = "حلول سلسة ونتائج قوية.",
                            ShortDescriptionEn = "Effortless Solutions. Powerful Results.",
                            Slug = "software-management-systems",
                            SortOrder = 4,
                            TitleAr = "أنظمة إدارة البرمجيات",
                            TitleEn = "Software Management Systems",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            AccentColor = "blue",
                            BodyAr = "بصفتنا الشريك الرسمي لـ GRGBanking في الإمارات، نوفر وندعم أحدث أجهزة الصراف الآلي وآلات الصراف الذكية (STM) وفرز النقد وأجهزة الخدمة الذاتية المصرفية. يحصل البنك على قنوات موثوقة للفروع والصالات، إضافة إلى أدوات مراقبة وتحقيق مدمجة تساعد على اكتشاف مشكلات الإيداع والأجهزة بشكل أسرع — لتقليص زمن المعالجة المعتاد من أيام إلى ساعات والحفاظ على ثقة العملاء.",
                            BodyEn = "As the official UAE partner for GRGBanking, Tayseer delivers and supports state-of-the-art ATMs, Smart Teller Machines (STMs), cash sorting, and self-service banking hardware. Banks get reliable branch and lobby channels, plus proprietary monitoring and investigation tools that help identify deposit and hardware issues faster — cutting typical resolution timelines from days to hours so customer trust stays intact.",
                            CtaLabelAr = "اعرف المزيد",
                            CtaLabelEn = "Learn More",
                            CtaUrl = "/solutions/banking-systems",
                            IconKey = "banking-systems",
                            IsPublished = true,
                            ShortDescriptionAr = "الشريك الرسمي لـ GRGBanking في الإمارات — أجهزة صراف وآلات صراف ذكية وأجهزة خدمة ذاتية للبنوك في المنطقة.",
                            ShortDescriptionEn = "Official UAE partner for GRGBanking — ATMs, smart teller machines, and self-service hardware for banks across the region.",
                            Slug = "banking-systems",
                            SortOrder = 6,
                            TitleAr = "حلول GRG Banking",
                            TitleEn = "GRG Banking",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Tayseer.Api.Domain.SiteSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ValueAr")
                        .HasColumnType("text");

                    b.Property<string>("ValueEn")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("Tayseer.Api.Domain.AgentConversation", b =>
                {
                    b.HasOne("Tayseer.Api.Domain.AdminUser", "AssignedAdminUser")
                        .WithMany()
                        .HasForeignKey("AssignedAdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedAdminUser");
                });

            modelBuilder.Entity("Tayseer.Api.Domain.AgentMessage", b =>
                {
                    b.HasOne("Tayseer.Api.Domain.AgentConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Tayseer.Api.Domain.PageSection", b =>
                {
                    b.HasOne("Tayseer.Api.Domain.Page", "Page")
                        .WithMany("Sections")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Tayseer.Api.Domain.ServiceFeature", b =>
                {
                    b.HasOne("Tayseer.Api.Domain.ServiceOffering", "ServiceOffering")
                        .WithMany("Features")
                        .HasForeignKey("ServiceOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceOffering");
                });

            modelBuilder.Entity("Tayseer.Api.Domain.AgentConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Tayseer.Api.Domain.Page", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Tayseer.Api.Domain.ServiceOffering", b =>
                {
                    b.Navigation("Features");
                });
#pragma warning restore 612, 618
        }
    }
}
