/** Legacy WordPress / static-HTML paths → locale-prefixed destinations. */
export const LEGACY_REDIRECTS: Record<string, string> = {
  '/about-us': '/en/about',
  '/about-us/': '/en/about',
  '/about-us.html': '/en/about',
  '/solutions': '/en/solutions',
  '/solutions/': '/en/solutions',
  '/solutions.html': '/en/solutions',
  '/core-banking': '/en/solutions/core-banking',
  '/core-banking/': '/en/solutions/core-banking',
  '/core-banking.html': '/en/solutions/core-banking',
  '/fahim-ai': '/en/solutions/fahim-ai',
  '/fahim-ai/': '/en/solutions/fahim-ai',
  '/fahim-ai.html': '/en/solutions/fahim-ai',
  '/mbuke': '/en/solutions/mbuke',
  '/mbuke/': '/en/solutions/mbuke',
  '/mbuke.html': '/en/solutions/mbuke',
  '/managed-services': '/en/managed-services',
  '/managed-services/': '/en/managed-services',
  '/managed-services.html': '/en/managed-services',
  '/software-management-systems': '/en/software-development',
  '/software-management-systems/': '/en/software-development',
  '/software-management-systems.html': '/en/software-development',
  '/banking-systems': '/en/solutions/banking-systems',
  '/banking-systems/': '/en/solutions/banking-systems',
  '/banking-systems.html': '/en/solutions/banking-systems',
  '/connect': '/en/contact',
  '/connect/': '/en/contact',
  '/connect.html': '/en/contact',
  '/careers': '/en/careers',
  '/careers/': '/en/careers',
  '/careers.html': '/en/careers',
  '/blogs-and-resources': '/en/faqs',
  '/blogs-and-resources/': '/en/faqs',
  '/blogs-and-resources.html': '/en/faqs',
  '/privacy-policy': '/en/legal/privacy',
  '/privacy-policy/': '/en/legal/privacy',
  '/privacy-policy.html': '/en/legal/privacy',
  '/privacy-policy-2': '/en/legal/privacy',
  '/privacy-policy-2/': '/en/legal/privacy',
  '/terms-conditions': '/en/legal/terms',
  '/terms-conditions/': '/en/legal/terms',
  '/terms-conditions.html': '/en/legal/terms',
  '/index.html': '/en',
};

/** In-app aliases that must 301 (not 200 duplicates). */
export const CANONICAL_REDIRECTS: Record<string, string> = {
  '/en/connect': '/en/contact',
  '/ar/connect': '/ar/contact',
  '/en/blog': '/en/faqs',
  '/ar/blog': '/ar/faqs',
};
